import * as THREE from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { EffectComposer } from 'three/examples/jsm/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/examples/jsm/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/examples/jsm/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/examples/jsm/postprocessing/OutputPass.js';
import { ViewerSimulation } from './sim.js';
import type { FaultMode, InterventionMode } from './sim.js';
import { WorldRenderer } from './worldRenderer.js';
import { TwinInspector } from './inspector.js';
import { createFacility } from './facility.js';
import { FacilityGraph } from './facilityGraph.js';
import { createIndustrialEnvironment } from './sceneEnvironment.js';

const app = document.getElementById('app')!;
const scene = new THREE.Scene();
createIndustrialEnvironment(scene);
scene.fog = new THREE.Fog(0x182127, 70, 175);

const camera = new THREE.PerspectiveCamera(48, innerWidth / innerHeight, 0.1, 1200);
camera.position.set(42, 28, 52);

const renderer = new THREE.WebGLRenderer({ antialias: true, powerPreference: 'high-performance' });
renderer.setPixelRatio(Math.min(devicePixelRatio, 1.5));
renderer.setSize(innerWidth, innerHeight);
renderer.shadowMap.enabled = true;
renderer.shadowMap.type = THREE.PCFSoftShadowMap;
renderer.toneMapping = THREE.ACESFilmicToneMapping;
renderer.toneMappingExposure = 1;
renderer.outputColorSpace = THREE.SRGBColorSpace;
app.appendChild(renderer.domElement);

const composer = new EffectComposer(renderer);
composer.addPass(new RenderPass(scene, camera));
composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth, innerHeight), 0.32, 0.65, 0.84));
composer.addPass(new OutputPass());

const controls = new OrbitControls(camera, renderer.domElement);
controls.target.set(10, 3, 2);
controls.enableDamping = true;
controls.dampingFactor = 0.06;

// Keep the existing tactical facility and add the reference repo's richer environment treatment.
createFacility(scene);

const facility = new FacilityGraph();
const sim = new ViewerSimulation();
const world = new WorldRenderer(scene);
const inspector = new TwinInspector();
const raycaster = new THREE.Raycaster();
const pointer = new THREE.Vector2();

const style = document.createElement('style');
style.textContent = `
  :root { --bg:#03070b; --glass:rgba(7,15,22,.72); --line:rgba(122,175,204,.18); --cyan:#55d7ff; --orange:#ff9b47; --red:#ff5f56; --green:#5fe3a1; --text:#eef8ff; --muted:#8ea6b6; --shadow:0 18px 60px rgba(0,0,0,.34); }
  *{box-sizing:border-box} html,body{margin:0;width:100%;height:100%;overflow:hidden;background:var(--bg);color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}
  button,select,input{font:inherit} button{transition:transform .16s ease,border-color .16s ease,background .16s ease,box-shadow .16s ease} button:hover{transform:translateY(-1px);border-color:rgba(85,215,255,.55)!important;box-shadow:0 8px 22px rgba(0,0,0,.18)} select:focus,input:focus{outline:none;border-color:rgba(85,215,255,.55);box-shadow:0 0 0 3px rgba(85,215,255,.09)}
  .hl-glass{background:linear-gradient(145deg,rgba(15,27,38,.78),rgba(4,10,15,.72));border:1px solid var(--line);box-shadow:var(--shadow),inset 0 1px 0 rgba(255,255,255,.035);backdrop-filter:blur(18px) saturate(130%);-webkit-backdrop-filter:blur(18px) saturate(130%);border-radius:18px}
  .hl-card{overflow:hidden;min-width:0;flex:0 0 auto}.hl-summary{list-style:none;cursor:pointer;padding:13px 14px;display:flex;align-items:center;justify-content:space-between;gap:10px;min-height:52px}.hl-summary::-webkit-details-marker{display:none}.hl-summary::after{content:'+';color:var(--muted);font-size:16px;flex:0 0 auto}details[open]>.hl-summary::after{content:'−';color:var(--cyan)}
  .hl-body{padding:0 14px 14px;min-width:0}.hl-body>*+*{margin-top:8px}.hl-kicker{color:var(--muted);text-transform:uppercase;letter-spacing:.12em;font-size:10px}.hl-section-title{font-weight:800;font-size:12px;letter-spacing:.06em;text-transform:uppercase}
  .hl-grid2{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:8px}.hl-grid3{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.hl-control{width:100%;min-width:0;padding:9px 10px;border-radius:10px;border:1px solid rgba(125,171,199,.2);background:rgba(5,13,20,.7);color:var(--text)}
  .hl-btn{width:100%;min-width:0;min-height:38px;padding:9px 10px;border-radius:10px;border:1px solid rgba(125,171,199,.18);background:rgba(11,24,33,.86);color:var(--text);font-weight:750;cursor:pointer;display:flex;align-items:center;justify-content:center;text-align:center;line-height:1.15;white-space:normal;overflow-wrap:anywhere}.hl-btn-primary{background:linear-gradient(180deg,rgba(255,119,57,.23),rgba(117,31,12,.38));border-color:rgba(255,128,65,.68);box-shadow:0 0 22px rgba(255,108,45,.16)}.hl-btn-green{border-color:rgba(95,227,161,.3)}.hl-btn-cyan{border-color:rgba(85,215,255,.34)}
  .hl-metrics{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:8px;margin-top:10px}.hl-metric{padding:10px 11px;min-width:0}.hl-metric-value{font-size:20px;font-weight:850;line-height:1;margin-top:5px}.hl-metric-label{color:var(--muted);font-size:9px;letter-spacing:.09em;text-transform:uppercase}
  .hl-cascade{display:flex;align-items:center;gap:6px;overflow-x:auto;overflow-y:hidden;padding:11px 12px 8px;scrollbar-width:thin;min-width:0}.hl-node{white-space:nowrap;border-radius:999px;padding:7px 10px;font:700 10px/1 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;border:1px solid rgba(85,215,255,.24);background:rgba(12,34,44,.82);color:#cdeffd;flex:0 0 auto}.hl-node.warn{border-color:rgba(255,155,71,.42);background:rgba(66,39,20,.64);color:#ffd9b7}.hl-node.critical{border-color:rgba(255,95,86,.56);background:rgba(65,18,17,.72);color:#ffd0cd}.hl-arrow{color:#557889;font-size:14px;flex:0 0 auto}
  .hl-riskbar{margin:0 12px 12px;padding:9px 10px;border-radius:10px;display:flex;align-items:center;justify-content:space-between;gap:8px;background:rgba(5,12,18,.62);border:1px solid var(--line)}.hl-risk-low{color:var(--green)}.hl-risk-escalate{color:var(--orange)}.hl-risk-critical{color:var(--red)}
  .hl-feed{display:grid;gap:6px;min-width:0}.hl-log{display:grid;grid-template-columns:48px 76px minmax(0,1fr);gap:7px;font:10px/1.35 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;color:#bfd3de;min-width:0}.hl-log span:last-child{min-width:0;overflow-wrap:anywhere}.hl-log-time{color:#6f8796}.hl-tag{border-radius:999px;padding:2px 6px;text-align:center;font-size:9px;font-weight:800}.hl-tag-info{background:rgba(85,167,255,.13);color:#9bc9ff}.hl-tag-warning{background:rgba(255,155,71,.14);color:#ffbf86}.hl-tag-cascade{background:rgba(255,95,86,.16);color:#ff9d97}.hl-tag-intervention{background:rgba(95,227,161,.13);color:#98f1c2}
  .hl-brand{display:flex;align-items:center;gap:9px;min-width:0}.hl-dot{width:9px;height:9px;border-radius:50%;background:var(--cyan);box-shadow:0 0 16px rgba(85,215,255,.8);flex:0 0 auto}.hl-scroll{flex:1 1 auto;min-height:0;min-width:0;overflow-x:hidden;overflow-y:auto;overscroll-behavior:contain;scrollbar-width:thin;scrollbar-color:rgba(85,215,255,.28) transparent}.hl-scroll::-webkit-scrollbar{width:7px}.hl-scroll::-webkit-scrollbar-thumb{background:rgba(85,215,255,.24);border-radius:999px}
  @media(max-width:1180px){.hl-metrics{left:328px!important;right:328px!important}}@media(max-width:960px){.hl-metrics{left:304px!important;right:304px!important;grid-template-columns:repeat(3,minmax(0,1fr))}.hl-summary{padding:11px 12px}.hl-body{padding:0 12px 12px}.hl-grid3{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:760px){.hl-metrics{left:12px!important;right:12px!important;top:82px!important;grid-template-columns:repeat(2,minmax(0,1fr))}.hl-metric{padding:9px 10px}.hl-metric-value{font-size:18px}.hl-grid2,.hl-grid3{grid-template-columns:1fr}.hl-summary{min-height:46px}.hl-log{grid-template-columns:42px 72px minmax(0,1fr)}}
`;
document.head.appendChild(style);

function text(value: string, muted = false) { const el=document.createElement('div'); el.textContent=value; if(muted) el.style.color='var(--muted)'; return el; }
function selectControl(options:{value:string;label:string}[],initial?:string){const s=document.createElement('select');s.className='hl-control';for(const option of options){const o=document.createElement('option');o.value=option.value;o.textContent=option.label;s.appendChild(o)}if(initial)s.value=initial;return s}
function button(label:string,fn:()=>void,variant=''){const b=document.createElement('button');b.textContent=label;b.className=`hl-btn ${variant}`.trim();b.onclick=fn;return b}
function card(title:string,subtitle='',open=true){const d=document.createElement('details');d.className='hl-glass hl-card';d.open=open;const summary=document.createElement('summary');summary.className='hl-summary';const left=document.createElement('div');left.innerHTML=`<div class="hl-section-title">${title}</div>${subtitle?`<div class="hl-kicker" style="margin-top:3px">${subtitle}</div>`:''}`;summary.appendChild(left);d.appendChild(summary);const body=document.createElement('div');body.className='hl-body';d.appendChild(body);return{root:d,body}}

const topBar=document.createElement('div');topBar.className='hl-glass';topBar.style.cssText='position:fixed;left:18px;right:18px;top:16px;height:58px;z-index:20;padding:11px 15px;display:flex;align-items:center;justify-content:space-between;gap:15px;min-width:0';document.body.appendChild(topBar);
const brand=document.createElement('div');brand.className='hl-brand';brand.innerHTML='<span class="hl-dot"></span><div><div style="font-size:15px;font-weight:900;letter-spacing:.05em">HAZARDLENS</div><div class="hl-kicker">TACTICAL DIGITAL TWIN · DER-02</div></div>';topBar.appendChild(brand);
const status=document.createElement('div');status.style.cssText='font:700 10px ui-monospace,monospace;color:var(--green);letter-spacing:.08em;white-space:nowrap';status.textContent='● FACILITY LINKED';topBar.appendChild(status);
const leftRail=document.createElement('div');leftRail.style.cssText='position:fixed;left:18px;top:88px;bottom:18px;width:340px;height:auto;z-index:15;display:flex;flex-direction:column;gap:10px;pointer-events:none;min-height:0';document.body.appendChild(leftRail);
const leftInner=document.createElement('div');leftInner.className='hl-scroll';leftInner.style.cssText='display:flex;flex-direction:column;gap:10px;pointer-events:auto;padding-right:4px';leftRail.appendChild(leftInner);
const disturbance=card('Primary Disturbance','choose what breaks',true);leftInner.appendChild(disturbance.root);
const assetSelect=selectControl([{value:'P-17',label:'PIPE P-17 · PROCESS LINE'},{value:'P-18',label:'PIPE P-18 · PROCESS LINE'},{value:'T-04',label:'TANK T-04 · STORAGE'},{value:'T-05',label:'TANK T-05 · STORAGE'},{value:'V-01',label:'VESSEL V-01 · PRESSURE'},{value:'R-01',label:'REACTOR R-01 · PROCESS'},{value:'HX-01',label:'HX-01 · HEAT EXCHANGER'},{value:'V-17',label:'VALVE V-17 · ISOLATION'},{value:'PUMP-01',label:'PUMP-01 · ROTATING EQUIPMENT'},{value:'COMP-01',label:'COMP-01 · COMPRESSOR'},{value:'W-07',label:'WALL W-07 · BARRIER'},{value:'COL-01',label:'COL-01 · STRUCTURE'},{value:'WIN-01',label:'WIN-01 · BUILDING'}]);disturbance.body.appendChild(text('TARGET',true));disturbance.body.appendChild(assetSelect);
const faultSelect=selectControl([{value:'leak',label:'LEAK · controlled release'},{value:'rupture',label:'RUPTURE · major release'},{value:'fire',label:'IGNITION · direct fire'},{value:'overheat',label:'OVERHEAT · thermal escalation'},{value:'overpressure',label:'OVERPRESSURE · vessel stress'},{value:'valve_fail',label:'VALVE FAILURE'},{value:'pump_fail',label:'PUMP / COMPRESSOR FAILURE'},{value:'power_loss',label:'POWER LOSS'},{value:'structural_damage',label:'STRUCTURAL DAMAGE'}]);disturbance.body.appendChild(text('DISTURBANCE',true));disturbance.body.appendChild(faultSelect);
const severityWrap=document.createElement('div');severityWrap.style.cssText='display:flex;align-items:center;gap:8px;margin-top:10px;min-width:0';severityWrap.appendChild(text('SEVERITY',true));const severity=document.createElement('input');severity.type='range';severity.min='0.1';severity.max='1';severity.step='0.1';severity.value='0.6';severity.style.flex='1';severity.style.minWidth='0';const sevValue=document.createElement('b');sevValue.textContent='60%';severity.oninput=()=>sevValue.textContent=`${Math.round(Number(severity.value)*100)}%`;severityWrap.append(severity,sevValue);disturbance.body.appendChild(severityWrap);
const windRow=document.createElement('div');windRow.className='hl-grid2';const windSelect=selectControl([{value:'East',label:'WIND → EAST'},{value:'West',label:'WIND → WEST'},{value:'North',label:'WIND → NORTH'},{value:'South',label:'WIND → SOUTH'}],'East');const weatherSelect=selectControl([{value:'stable',label:'ATMOSPHERE · STABLE'},{value:'neutral',label:'ATMOSPHERE · NEUTRAL'},{value:'unstable',label:'ATMOSPHERE · UNSTABLE'}],'neutral');windRow.append(windSelect,weatherSelect);disturbance.body.appendChild(windRow);
const inject=button('⚠  INJECT DISTURBANCE',()=>{const winds:Record<string,[number,number]>={East:[3,0],West:[-3,0],North:[0,-3],South:[0,3]};const[windX,windZ]=winds[windSelect.value];sim.injectIncident({assetId:assetSelect.value,mode:faultSelect.value as FaultMode,severity:Number(severity.value),windX,windZ})},'hl-btn-primary');disturbance.body.appendChild(inject);
const response=card('Response & Countermeasures','act on the simulated facility',true);leftInner.appendChild(response.root);const responseGrid=document.createElement('div');responseGrid.className='hl-grid2';for(const[label,mode,cls]of[['ISOLATE SOURCE','isolate','hl-btn-cyan'],['COOL EXPOSED','cool','hl-btn-cyan'],['SUPPRESS FIRE','suppress','hl-btn-green'],['EVACUATE ZONE','evacuate','hl-btn-green'],['EMERGENCY SHUTDOWN','shutdown',''],['FIRE MONITOR','fire_monitor','']]as[string,InterventionMode,string][])responseGrid.appendChild(button(label,()=>sim.intervene(mode),cls));response.body.appendChild(responseGrid);
const simControls=card('Simulation Controls','time, replay and inspection',true);leftInner.appendChild(simControls.root);const simGrid=document.createElement('div');simGrid.className='hl-grid3';simGrid.appendChild(button('PAUSE',()=>sim.running=false));simGrid.appendChild(button('RESUME',()=>sim.running=true,'hl-btn-cyan'));simGrid.appendChild(button('RESET',()=>{sim.reset();inspector.show()}));simControls.body.appendChild(simGrid);const speed=selectControl([{value:'0.5',label:'0.5×'},{value:'1',label:'1×'},{value:'2',label:'2×'},{value:'4',label:'4×'}],'1');simControls.body.appendChild(speed);speed.onchange=()=>sim.speed=Number(speed.value);
const cascadeCard=card('Domino Cascade Chain','live consequence propagation',true);leftInner.appendChild(cascadeCard.root);const cascade=document.createElement('div');cascade.className='hl-cascade';cascade.innerHTML='<div class="hl-kicker">Awaiting initiating event…</div>';cascadeCard.body.appendChild(cascade);const riskBar=document.createElement('div');riskBar.className='hl-riskbar';riskBar.innerHTML='<span class="hl-kicker">DOMINO RISK</span><b class="hl-risk-low">LOW</b>';cascadeCard.body.appendChild(riskBar);
const rightRail=document.createElement('div');rightRail.style.cssText='position:fixed;right:18px;top:88px;bottom:18px;width:360px;height:auto;z-index:15;display:flex;flex-direction:column;gap:10px;pointer-events:none;min-height:0';document.body.appendChild(rightRail);const rightInner=document.createElement('div');rightInner.className='hl-scroll';rightInner.style.cssText='display:flex;flex-direction:column;gap:10px;pointer-events:auto;padding-left:4px';rightRail.appendChild(rightInner);const feedCard=card('Live Event Stream','causal event fabric',true);rightInner.appendChild(feedCard.root);const eventFeed=document.createElement('div');eventFeed.className='hl-feed';feedCard.body.appendChild(eventFeed);const selectedCard=card('Twin Inspector','click an asset in the facility',false);rightInner.appendChild(selectedCard.root);
const metrics=document.createElement('div');metrics.className='hl-metrics';metrics.style.cssText+='position:fixed;left:378px;right:396px;top:88px;z-index:14;';document.body.appendChild(metrics);const metricValues=new Map<string,HTMLElement>();for(const[key,label]of[['time','TIME'],['fire','FIRES'],['release','RELEASES'],['cascade','DOMINO ESC.'],['personnel','PERSONNEL RISK']]){const m=document.createElement('div');m.className='hl-glass hl-metric';m.innerHTML=`<div class="hl-metric-label">${label}</div><div class="hl-metric-value">0</div>`;metrics.appendChild(m);metricValues.set(key,m.querySelector('.hl-metric-value') as HTMLElement)}
const cascadeLabel=(eventType:string)=>{const map:Record<string,string>={'fault.pipe_leak':'Pipe Failure','release.created':'Vapor Cloud','release.ignited':'Ignition','fire.created':'Fire Escalation','thermal.exposure':'Thermal Exposure','overpressure.received':'Overpressure','asset.degraded':'Asset Degraded','asset.failed':'Secondary Failure','route.blocked':'Route Blocked','geometry.changed':'Structural Change','suppression.command':'Suppression','cooling.command':'Cooling','valve.command':'Isolation','shutdown.command':'Emergency Shutdown','evacuation.command':'Evacuation'};return map[eventType]??eventType.replaceAll('.',' ')};
const severityOf=(type:string)=>{if(type.includes('asset.failed')||type.includes('fire')||type.includes('release.ignited')||type.includes('overpressure'))return['CASCADE','critical']as const;if(type.includes('thermal')||type.includes('degraded')||type.includes('fault')||type.includes('release'))return['WARNING','warn']as const;if(type.includes('command'))return['INTERVENTION','']as const;return['INFO','']as const};
renderer.domElement.addEventListener('pointerdown',e=>{pointer.x=e.clientX/innerWidth*2-1;pointer.y=-(e.clientY/innerHeight)*2+1;const selected=world.pick(raycaster,camera,pointer);if(selected){const zone=facility.findZone(selected.id);selected.metadata.zone=zone?.name??'unassigned';selected.metadata.connections=facility.neighbors(selected.id).join(',')}inspector.show(selected)});
let last=performance.now();function frame(now:number){requestAnimationFrame(frame);const dt=(now-last)/1000;last=now;sim.update(dt);const snap=sim.snapshot();world.sync(snap);const activeFires=snap.twins.filter(t=>t.kind==='fire'&&t.active).length;const activeReleases=snap.twins.filter(t=>t.kind==='release'&&t.active).length;const failed=snap.twins.filter(t=>!t.active&&!['fire','release'].includes(t.kind)).length;const escalationEvents=snap.events.filter(e=>['asset.failed','fire.created','release.ignited','overpressure.received','route.blocked'].includes(e.type)).length;const personnelRisk=snap.twins.filter(t=>t.kind==='worker').reduce((sum,t)=>sum+Number(t.metadata.exposure??0),0);const riskScore=activeFires*18+activeReleases*12+failed*20+escalationEvents*4+personnelRisk*.1;const riskLevel=riskScore>=70?'CRITICAL':riskScore>=30?'ESCALATE':'LOW';const riskClass=riskScore>=70?'hl-risk-critical':riskScore>=30?'hl-risk-escalate':'hl-risk-low';metricValues.get('time')!.textContent=`${snap.time.toFixed(1)}s`;metricValues.get('fire')!.textContent=String(activeFires);metricValues.get('release')!.textContent=String(activeReleases);metricValues.get('cascade')!.textContent=String(escalationEvents);metricValues.get('personnel')!.textContent=personnelRisk>40?'HIGH':personnelRisk>10?'MED':'LOW';riskBar.innerHTML=`<span class="hl-kicker">DOMINO RISK · ${riskScore.toFixed(0)}</span><b class="${riskClass}">${riskLevel}</b>`;const cascadeEvents=snap.events.filter(e=>['fault.pipe_leak','release.created','release.ignited','fire.created','thermal.exposure','overpressure.received','asset.degraded','asset.failed','route.blocked','geometry.changed'].includes(e.type)).slice(-6);if(cascadeEvents.length===0)cascade.innerHTML='<div class="hl-kicker">Awaiting initiating event…</div>';else{cascade.innerHTML='';cascadeEvents.forEach((e,i)=>{const[sev,cls]=severityOf(e.type);const node=document.createElement('div');node.className=`hl-node ${cls}`;node.textContent=cascadeLabel(e.type);cascade.appendChild(node);if(i<cascadeEvents.length-1){const arrow=document.createElement('span');arrow.className='hl-arrow';arrow.textContent='➜';cascade.appendChild(arrow)}})}const recent=snap.events.slice(-8).reverse();eventFeed.innerHTML=recent.length?recent.map(e=>{const[tag]=severityOf(e.type);const tagClass=tag==='CASCADE'?'hl-tag-cascade':tag==='WARNING'?'hl-tag-warning':tag==='INTERVENTION'?'hl-tag-intervention':'hl-tag-info';const stamp=`${e.time.toFixed(1)}s`;const msg=`${cascadeLabel(e.type)}${e.targetId?` · ${e.targetId}`:''}`;return`<div class="hl-log"><span class="hl-log-time">${stamp}</span><span class="hl-tag ${tagClass}">${tag}</span><span>${msg}</span></div>`}).join(''):'<div class="hl-kicker">Awaiting incident…</div>';selectedCard.body.innerHTML='<div class="hl-kicker">Select any tank, pipe, valve, structure or response asset in the 3D scene to inspect its live state.</div>';controls.update();composer.render()}requestAnimationFrame(frame);
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight)});
